Fixed some problems.
The setup problem still remains. In self.remote_conn.getnewaddress() a new connection should be made, but I get:
"for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known"
which is one of the socket errors.